export const CONSTANTES = {
    TipoExcepciones: {
        REQUISITOS_CON_RECEPCION_FISICA: 13,
        DGTA_MULTIPLES_PAGOS: 14,
        INCREMENTO_SUSTITUCION_DE_FLOTA_DE_TRANSPORTE_FLUVIAL: 15,
    },
    EstadoRequisito: {
        COD_EST_REQ_PEN_REVISION: 9,
        COD_EST_REQ_APRO_P_TASA: 31,
        COD_EST_REQ_APROBADO: 10,
    },
    CodTabTipoPersona: {
        PERSONA_NATURAL: '00001',
        PERSONA_JURIDICA: '00002',
        PERSONA_NATURAL_JURIDICA: '00003',
        PERSONA_EXTRANJERA: '00004',
        PERSONA_NATURAL_CON_RUC: '00005',
        PERSONA_JURIDICA_O_PERSONA_NATURAL_CON_RUC: '00006',
        PERSONA_CARNE_SOLICITANTE_REFUGIO: '00010',
    },
    TipoDocPersona: {
        RUC: '00001',
        DNI: '00002',
        CARNET_EXTRANJERIA: '00003',
        CARNET_SOLICITANTE_REFUGIO: '00101',
        CARNET_PERMISO_TEMPORAL_PERMANENCIA: '00102',
        CARNET_IDENTIFICACION: '00103',
        PASAPORTE: '00005',
    },
    TipoDocPersonaExtranjera: {
        CARNET_EXTRANJERIA: '00003',
        CARNET_SOLICITANTE_REFUGIO: '00101',
        CARNET_PERMISO_TEMPORAL_PERMANENCIA: '00102',
        CARNET_IDENTIFICACION: '00103',
        PASAPORTE: '00005',
    },
    TipoDocPersonaPasarela: {
        DNI: 1,
        CARNET_FFPP: 2,
        CARNET_FFAA: 3,
        CARNET_EXTRANJERIA: 4,
        PASAPORTE: 5,
        RUC: 6,
        PARTIDA_NACIMIENTO: 9,
        CEDULA_DIPLOMATICA_IDENTIDAD: 16,
        OTRAS: 19
    },
    CodMaeCatRequisito: {
        FRACCIONAMIENTO_DE_PAGO: 1,
        SEGUNDO_FRACCIONAMIENTO_DE_PAGO: 2,
        EXPERIENCIA_MEDIANTE_CONTRATO_GESTIÓN: 3,
        CONSORCIO: 4,
        EVALUACIÓN_TEORICA: 163,
        EVALUACIÓN_PRACTICA: 164,
    },
    CodRegModuloRol: {
        TRAMITE_ADMINISTRADOR_TUPA: 1,
        TRAMITE_COORDINADOR_TUPA: 2,
        TRAMITE_GESTOR_OACGD: 7,
        TRAMITE_GESTOR_CIUDADANO: 8,
    },
    MaeConCatRequisito: {
        TIPOLIQUID_INTERNACIONAL: '0',
        TIPOLIQUID_NACIONAL: '1',
        TIPOLIQUID_AMBOS: '2',
        CODPADRE_VUELONACIONAL: 238,
        CODPADRE_VUELOINTERNACIONAL: 239,
        TIPOCONCEPTO_TITULO: '0',
        TIPOCONCEPTO_DESCRIPCION: '1',
        TIPOCONCEPTO_GENERAL: '2',
        COD_PER_AER_VUE_INT_TRP_TECNICOS: 236,
        COD_PER_AER_VUE_INT_TRP_AUXILIARES: 237,
        COD_PER_TIERRA: 232,
        COD_PER_MANTENIMIENTO: 233,
        COD_PER_AER_VUE_NAC_TRP_TECNICOS: 234,
        COD_PER_AER_VUE_NAC_TRP_AUXILIARES: 235,
    },
    MaeTupa: {
        COD_MAE_TUPA_DGAC_004: 'DGAC-004',
        COD_MAE_TUPA_DGAC_005: 'DGAC-005',
        COD_TUPA_PRONATEL_001: 'PRONATEL-001',
        COD_TUPA_DGPRC_001: 'DGPRC-001',
        COD_TUPA_DGPP_001: 'DGPP-001',
        COD_TUPA_DGPP_002: 'DGPP-002',
        COD_TUPA_DGC_001: 'DGC-001',
        COD_TUPA_DGC_002: 'DGC-002',
        COD_TUPA_DGAAM_001: 'DGAAM-001',
        COD_TUPA_DGAAM_002: 'DGAAM-002',
        COD_TUPA_DGPPC_005: 'DGPPC-005',
        COD_TUPA_DGPPC_006: 'DGPPC-006',
        ID_TUPA_DGAAM_001: 33,
        ID_TUPA_DGAAM_002: 34,
        ID_TUPA_DSTT_032: 181,
        ID_TUPA_DGAT_012: 48,
        ID_TUPA_DGAC_023: 183,
        ID_TUPA_DGC_007: 186,
    },
    CodDesPreliquidacion: {
        EVAL_PERS_AERON_PRACTICA_PERS_AEREO_VUELO_INTERNACIONAL: '020174',
        EVAL_PERS_AERON_PRACTICA_PERS_AEREO_VUELO_INTERNACIONAL_Tt_Tt: '020173',
        EVAL_PERS_AERON_PRACTICA_PERS_AEREO_VUELO_NACIONAL_Tt_Aa: '020172',
        EVAL_PERS_AERON_PRACTICA_PERS_AEREO_VUELO_NACIONAL: '020171',
        EVAL_PERS_AERON_PRACTICA_PERS_DE_TIERRA_MANTENIMIENTO: '020170',
        POR_DIA_VIATICO_1: '020253',
        POR_DIA_VIATICO_2: '020252',
        NOM_020174: 'Eval. Person-practica Pers Aereo Vuelo Internacional',
        NOM_020173: 'Eval. Person-practica Pers Aereo Vuelo Internacional Tt Tt',
        NOM_020172: 'Eval. Person-practica Pers Aereo Vuelo Nacional Tt Aa',
        NOM_020171: 'Eval. Tipo de Cabina Pers Aereo Vuelo Nacional',
        NOM_020170: 'Eval. Tipo de Cabina Pers de Tierra Mantenimiento',
        NOM_020253: 'Por día de Viático',
        NOM_020252: 'Por día de Viático',
    },
    EstadoSolicitud: {
        COD_MAE_ESTADO_PENDIENTE: 'PENDIENTE',
    },
    MensajeError: {
        Sunat: 'En estos momentos no podemos conectarnos con el servicio de la SUNAT, por favor inténtelo más tarde, o póngase en contacto con nosotros.',
        Reniec: 'En estos momentos no podemos conectarnos con el servicio de RENIEC, por favor inténtelo más tarde, o póngase en contacto con nosotros.',
        Migraciones: 'En estos momentos no podemos conectarnos con el servicio de MIGRACIONES, por favor inténtelo más tarde, o póngase en contacto con nosotros.',
        RepLegNotFound: 'El tipo y/o número de documento ingresado no corresponde a ningún representante legal registrado en la SUNAT.',
        UpdateRepLegSunat: 'En estos momentos no podemos conectarnos con el servicio de la SUNAT, no podrá cambiar de representante legal, por favor inténtelo más tarde, o póngase en contacto con nosotros.',
    },
    ComboGenericoFTAW: {
        TipoMuestra: 'TIPO_MUESTRA',
        ClaseMonitoreo: 'CLASE_MONITOREO',
        ZonaMuestreo: 'UBICACION_MONITOREO',
        TipoProcedencia: 'ZONA_MUESTREO',
        FrecuenciaMonitoreo: 'FREC_MONIT',
        FrecuenciaReporte: 'FREC_REPORTE',
        Zona: 'ZONA',
        Datum: 'DATUM'
        //ClaseMonitoreo:'LST_TipoMonitoreo',
    },
    ComboGenericoDIAW: {
        EtapaFase: 'MAESTRA',
        Etapa: 'ETAPA_AMBIENTAL',
        TipoActividad: 'TIPO_ACTIVIDAD',
        TipoMoneda: 'TIPO_MONEDA',
        Zona: 'ZONA',
        Datum: 'DATUM'
    },
    ComboGenericoEIAW: {
        TipoEstudio: 'TIPO_ESTUDIO',
        TipoDocumento: 'TIPO_DOCUMENTO'
    },
    Datum: "2",
    FilesTemplates: {
        Plataformas: 'ArchivoTemplate_ImportPlataformas.csv',
    },
    FormDia: {
        RESUMEN_EJECUTIVO: 'ResumenEjecutivo',
        DESCRIPCION_PROYECTO: 'DescripcionProyecto',
        OBJETIVO: 'Objetivo',
        LOCALIZACION_GEOGRAFICA: 'LocalizacionGeografica',
        DELIMITACION: 'Delimitacion',
        AREAS_INFLUENCIA: 'AreasInfluencia',
        CRONOGRAMA_INVERSION: 'CronogramaInversion',
        DESCRIPCION_ETAPAS: 'DescripcionEtapas',
        DESCRIPCION_MEDIO_FISICO: 'DescripcionMedioFisico',
        DESCRIPCION_MEDIO_BIOLOGICO: 'DescripcionMedioBiologico',
        PUNTO_MUESTREO: 'PuntoMuestreo',
        DESCRIPCION_ASPECTO_SOCIAL: 'DescripcionAspectoSocial',
        ARQUEOLOGIA: 'Arqueologia',
        CARTOGRAFIA: 'Cartografia',
        PARTICIPACION_CIUDADANA: 'ParticipacionCiudadana',
        IMPACTOS_AMBIENTALES: 'ImpactosAmbientales',
        PLAN_MANEJO_AMBIENTAL: 'PlanManejoAmbiental',
        PLAN_VIGILANCIA_AMBIENTAL: 'PlanVigilanciaAmbiental',
        PLAN_MINIMIZACION: 'PlanMinimizacion',
        PLAN_CONTINGENCIA: 'PlanContingencia',
        PROTOCOLO_RELACIONAMIENTO: 'ProtocoloRelacionamiento',
        PLAN_CIERRE: 'PlanCierre',
        RESUMEN: 'Resumen',
        CONSULTORA: 'Consultora',
        SOLICITUD_TITULO: 'SolicitudTitulo'
    },
    MsgFormDia: {
        MSG_0011_RESUMEN_EJECUTIVO: '-Descripción del Resumen Ejecutivo',
        MSG_0012_ADJUNTAR_RESUMEN_EJECUTIVO: '-Falta Adjuntar Archivo en la Sección ADJUNTAR ARCHIVOS',
        MSG_0211_NOMBRE_PROYECTO: '-Nombre del Proyecto',
        MSG_0211_INVERSION_ESTIMADA: '-Inversión estimada del Proyecto',
        MSG_0211_CORREOS_NOTIFICACION: '-Correos de Notificacion Inválidos',
        MSG_0211_UNIDAD_MINERA: '-Debe seleccionar Unidad Minera',
        MSG_0216_ESTUDIOS: '-Estudios e Investigaciones previas',
        MSG_0212_DERECHOS_MINEROS: '-Derechos mineros del solicitante',
        MSG_2151_MAPA_COMPONENTES: '-Falta Adjuntar Archivo en la Sección MAPA DE UBICACIÓN COMPONENTES PREVIOS',
        MSG_0217_PERMISOS_LICENCIAS: '-Permisos, Licencias y/o Permisos Existentes',
        MSG_0218_PROPIEDAD_SUPERFICIAL: '-Falta Adjuntar Archivo en la Seccion MAPA DE PROPIEDAD SUPERFICIAL',
        MSG_2193_MAPA_AREAS_NATURALS: '-No existe Mapa de Areas Naturales protegidasL',
        MSG_0022_DESCRIPCION_OBJETIVO: '-Descripción del Objetivo',
        MSG_0232_LOCALIZACION_SUPERPUESTA: '-Falta Adjuntar Archivo en la Sección LOCALIZACION SUPERPUESTA AL AREA EFECTIVA DEL PROYECTO',
        MSG_0233_DISTANCIA_POBLADOS: '-Distancia Poblados Cercanos',
        MSG_0241_AREAS_ACTIVIDAD_MINERA: '-AREAS SUPERFICIALES EN ACTIVIDAD MINERA',
        MSG_0242_COORDENADAS_ESTE: '-COORDENADAS DEL PUNTO ESTE',
        MSG_0242_COORDENADAS_NORTE: '-COORDENADAS DEL PUNTO NORTE',
        //MSG_0242_ZONA: 'ZONA', 
        //MSG_0242_DATUM: 'DATUM'   
        MSG_0243_MAPA_EFECTIVA: '-Falta Adjuntar Archivo en la Seccion MAPA DE AREA EFECTIVA',
        MSG_0251_AREAS_DIRECTA_AMBIENTAL: '-Area Directa Ambiental',
        MSG_0252_AREAS_INDIRECTA_AMBIENTAL: '-Area Indirecta Ambiental',
        MSG_0253_AREAS_DIRECTA_SOCIAL: '-Area Directa Social',
        MSG_0254_AREAS_INDIRECTA_SOCIAL: '-Area Indirecta Social',
        MSG_0255_ARCHIVOS_ESCANEADOS: '-Falta Adjuntar Archivo en la Seccion ADJUNTAR ARCHIVOS ESCANEADOS',
        MSG_0026_CRONOGRAMA: '-Faltan datos en Cronograma',       
        MSG_0271_MINERAL_EXPORTAR: '-Mineral a explotar',
        MSG_0272_COMPONENTES_PRINCIPALES: '-Componentes Principales',
        MSG_2752_DEMANDA_AGUA: '-Falta Adjuntar Archivo en la Seccion DEMANDA AGUA',
        MSG_2731_COMPONENTES_PROYECTO: '-Componentes del proyecto',
        MSG_2733_TOPSOIL : '-Falta Adjuntar Archivo en la Seccion MANEJO DE TOPSOIL',
        MSG_0274_RESIDUOS_GENERAR: '-Residuos a generar',
        MSG_2751_REQUERIMIENTO_AGUA: '-Requerimiento de Agua',
        MSG_2753_BALANCE_AGUA: '-Falta Adjuntar Archivo en la Seccion BALANCE DE AGUA',
        MSG_0276_INSUMOS_PROYECTO: '-Insumos del proyecto',
        MSG_0276_MANEJO_EFLUENTES: '-Falta Adjuntar Archivo en la Seccion MANEJO DE EFLUENTES Y EMISIONES',
        MSG_2772_MAQUINARIAS: '-Maquinarias',
        MSG_2773_EQUIPOS: '-Equipos',
        MSG_2774_MDS: '-Falta Adjuntar Archivo en la Seccion ADJUNTAR ARCHIVOS MDS',
        MSG_2781_VIAS_EXISTENTES: '-Vias de acceso existentes',
        MSG_2782_VIAS_NUEVAS: '-Vias de acceso Nuevas',
        MSG_2710_FUENTE_ENERGIA: '-Fuente de Energia',
        MSG_2711_CIERRE_POSTCIERRE: '-Cierre y Postcierre',
        MSG_2712_MAPA_COMPONENTES: '-Falta Adjuntar Archivo en la Seccion MAPA DE COMPONENTES',
        MSG_2791_TIPO_MANO_OBRA: '-Origen de personal',
        MSG_0279_MANO_OBRA: '-Faltan datos en Personal',
        MSG_0027_DOCUMENTO: '-Falta Adjuntar Archivo en la Seccion ADJUNTAR DISEÑOS TECNICOS',
        MSG_0311_METEOROLOGIA: '-Metereologia y Clima: Dato obligatorio',
        MSG_0312_CALIDAD_AIRE: '-Calidad de Aire: Dato obligatorio',
        MSG_0313_CALIDAD_RUIDO: '-Calidad de Ruido Ambiental: Dato obligatorio',
        MSG_3141_TOPOGRAFIA: '-Topografia: Dato obligatorio',
        MSG_3142_GEOLOGIA: '-Geologia: Dato obligatorio',
        MSG_3143_GEOMORFOLOGIA: '-Geomorfologia: Dato obligatorio',
        MSG_3152_HIDROGRAFIA: '-Hidrografia: Dato obligatorio',
        MSG_3152_HIDROGEOLOGIA: '-Hidrogeologia: Dato obligatorio',
        MSG_3154_CALIDAD_AGUA: '-Calidad del Agua Superficial: Dato obligatorio',
        MSG_3161_ESTUDIO_SUELO: '-Hidrologia: Dato obligatorio',
        MSG_3162_CLASIFICACION_TIERRAS: '-Clasificacion de las tierras por capacidad de uso mayor: Dato obligatorio',
        MSG_3163_USO_TIERRAS: '-Uso actual de la tierra: Dato obligatorio',
        //MSG_3164_CALIDAD_SUELOS: '-Calidad de los suelos',
        //MSG_0321_CRITERIOS: '-Criterios de Evaluacion: Dato obligatorio',
        //MSG_0322_DESCRIPCION_ECOSISTEMA: '-Descripcion de Ecosistemas: Dato obligatorio',
        MSG_3221_ECOSISTEMAS: '-Ecosistemas: Dato obligatorio',
        MSG_3222_FLORA_TERRESTRE: '-Flora Terrestre: Dato obligatorio',
        MSG_3223_FAUNA_TERRESTRE: '-Fauna Terrestre: Dato obligatorio',
        //MSG_3224_FAUNA_TERRESTRE: '-Hidrobiologia: Dato obligatorio',
        MSG_3225_ECOSISTEMAS_FRAGILES: '-Ecosistemas Fragiles: Dato obligatorio',
        //MSG_3226_AREAS_NATURALES: '-Areas Naturales: Dato obligatorio',
        MSG_0032_DOCUMENTOS: '-Falta Adjuntar Archivo en la Seccion ARCHIVOS ADJUNTOS',
        MSG_0331_PUNTO_MUESTREO: '-Falta Adjuntar Archivo en la Sección PUNTOS DE MUESTREO',
        MSG_0342_DESCRIPCION: '-Descripcion: Dato obligatorio',
        MSG_0341_INDICES: '-Indices: Dato obligatorio',
        MSG_0343_OTROS_ASPECTOS: '-OtrosAspectos: Dato obligatorio', 
        //MSG_0351_DESCRIPCION: '-Descripcion: Dato obligatorio',
        MSG_0035_DOCUMENTOS: '-Falta Adjuntar Archivo en la Seccion ADJUNTAR ARCHIVOS',
        MSG_0036_CARTOGRAFIA: '-Falta Adjuntar Archivo en la Seccion ADJUNTAR ARCHIVOS',
        MSG_0041_MECANISMOS: '-Acceso de la población a Resúmenes Ejecutivos y al contenido del texto completo del estudio ambiental en la fase ANTES DE LA PRESENTACION DE ESTUDIO',
        MSG_00411_MECANISMO_TALLERES: '-Talleres Informativos y Participativos en la fase ANTES DE LA PRESENTACION DE ESTUDIO',
        MSG_00411_MECANISMO_RESUMENES: '-Acceso de la población a Resúmenes Ejecutivos y al contenido del texto completo del estudio ambiental en la fase ANTES DE LA PRESENTACION DE ESTUDIO',
        MSG_0042_DOCUMENTOS: '-Falta Adjuntar Archivo en la Seccion ADJUNTAR ARCHIVOS ESCANEADOS',
        MSG_0051_IMPACTO_AMBIENTAL: '-Falta Adjuntar Archivo en la Seccion ADJUNTAR ARCHIVOS ESCANEADOS',
        MSG_0611_PLAN_MANEJO: '-Plan de Manejo Ambiental',
        MSG_0621_PUNTOS_MONITOREO: '-Plan de Manejo Ambiental',
        MSG_0622_DOCUMENTOS: '-Falta Adjuntar Archivo en la Seccion ADJUNTAR ARCHIVOS ESCANEADOS',
        MSG_0631_DESCRIPCION: '-Descripcion del plan de minizacion y manejo de residuos',
        MSG_0064_DESCRIPCION: '-Descripcion del Plan de Contingencia',
        MSG_0065_DESCRIPCION: '-Descripcion del Protocolo de Relacionamiento',
        MSG_0661_DESCRIPCION_CIERRE: '-Descripcion del Cierre',
        MSG_0662_DESCRIPCION_POST_CIERRE: '-Descripcion del PostCierre',
        MSG_0671_COMPROMISOS: '-Plan de Manejo Ambiental',
        //MSG_0671_MONTO_INVERSION: '-MONTO TOTAL ESTIMADO DE INVERSIÓN',
        MSG_0671_UNIDAD_MONETARIA: '-Seleccione tipo de Moneda en Plan de Manejo Ambiental',
        MSG_0672_DOCUMENTOS: '-Falta Adjuntar Archivo en la Seccion ADJUNTAR ARCHIVOS ESCANEADOS',
        //MSG_0071_NOMBRE_CONSULTORA: '-Empresa Consultora',  
        MSG_0072_PROFESIONAL_CONSULTORA: '-Profesionales que realizaron el estudio',
        //MSG_0073_OTRO_PROFESIONAL_CONSULTORA: '-Otros Profesionales',  
        MSG_0074_DOCUMENTOS: '-Adjuntar certificado de habilidad',
        MSG_0081_SOLICITA_TITULO: '-Seleccione Solicitud de título habilitante'
    },
    StateToIconMap: {
        1: 'warning',
        2: 'done',
        3: 'close'
    },
    StateToIconClassMap: {
        1: 'incomplete',
        2: 'complete',
        3: 'error'
    },
    StateIconToIconClassMap: {
        'warning': 'incomplete',
        'done': 'complete',
        'close': 'error'
      },
    CapituloFormDia: {
        0: '1',
        2: '2.1',
        3: '2.2',
        4: '2.3',
        5: '2.4',
        6: '2.5',
        7: '2.6',
        8: '2.7',
        10: '3.1',
        11: '3.2',
        12: '3.3',
        13: '3.4',
        14: '3.5',
        15: '3.6',
        16: '4',
        17: '5',
        19: '6.1',
        20: '6.2',
        21: '6.3',
        22: '6.4',
        23: '6.5',
        24: '6.6',
        25: '6.7',
        26: '7',
        27: '8'
    }
};
